# Site settings
title: The Wheelhouse Street Fare
email: wheelhousefood@gmail.com
description: >
  The Wheelhouse serves delicious fusion dishes. We use high quality
  ingredients, focusing on Thai and Mexican food and exploring other culinary
  traditions.
baseurl: "/wheelhousefood.com" # the subpath of your site, e.g. /blog/
url: "http://wheelhousefood.com" # the base hostname & protocol for your site
facebook_username: wheelhousefood
twitter_username: wheelhousefood
google_username: 102749925529009691414
exclude: [node_modules, package.json, script, webpack.config.js]

collections:
  specials:
    output: true
    permalink: "/specials/:name/"

defaults:
  -
    scope:
      path: ""
      type: specials
    values:
      layout: special

# Build settings
markdown: kramdown

# prose.io configuration
prose:
  media: media
  ignore:
    - .gitignore
    - _config.yml
    - _includes
    - _js
    - _layouts
    - _sass
    - about.md
    - feed.xml
    - index.html
    - js
    - package.json
    - script
    - webpack.config.js
