# Site settings
title: The Wheelhouse Street Fare
email: wheelhousefood@gmail.com
description: >
  The Wheelhouse serves delicious fusion dishes. We use high quality
  ingredients, focusing on Thai and Mexican food and exploring other culinary
  traditions.
baseurl: "https://wheelhousefood.com" # the subpath of your site, e.g. /blog/
facebook_username: wheelhousefood
twitter_username: wheelhousefood
instagram_username: wheelhousefood
google_username: 102749925529009691414
exclude: [bin, node_modules, package.json, webpack.config.js]

collections:
  specials:
    output: true
    permalink: "/specials/:name/"

defaults:
  -
    scope:
      path: ""
      type: specials
    values:
      layout: special

# prose.io configuration
prose:
  media: media
  metadata:
    _specials:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: true
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME

  ignore:
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - _config.yml
    - _includes
    - _js
    - _layouts
    - _posts
    - _sass
    - bin
    - feed.xml
    - images
    - index.html
    - js
    - menu.md
    - package.json
    - webpack.config.js
